# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - main
    - dev

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\build\installBuildDependencies.ps1'
    arguments: ''

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\build.ps1'
    arguments: ''

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/*-nunit.xml'
    failTaskOnFailedTests: true

- task: PowerShell@2
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\build.ps1'
    arguments: '-Apikey $(PSGalleryApiKey) -Publish'
