# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - '*'
  branches:
    exclude:
    - main
    - dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\DNSDebugLogHandler\dependency.ps1'
    arguments: ''

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Pester@10
  inputs:
    scriptFolder: '$(System.DefaultWorkingDirectory)\*'
    resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
    usePSCore: False

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\DNSDebugLogHandler\publish.ps1'
    arguments: '-Apikey $(PSGalleryApiKey)'
